from __future__ import annotations

import re
from typing import Any

from app.core.taxonomy_catalog import ALGORITHMS, TECHNIQUES


def taxonomy_slug(value: str) -> str:
    slug = re.sub(
        r"\s+",
        "-",
        re.sub(r"[^a-z0-9\s-]", " ", str(value or "").lower().replace("/", " ").replace("&", " ").replace("-", " ")).strip(),
    )
    return {
        "heap-priority-queue": "heap",
        "dfs-bfs": "dfs-bfs",
    }.get(slug, slug)


def _entry(
    title: str,
    algorithm: str,
    skills: tuple[str, ...],
    techniques: tuple[str, ...],
    difficulty: str,
    description: str,
    examples: tuple[str, ...],
) -> dict[str, Any]:
    assert algorithm in ALGORITHMS, f"unknown algorithm slug: {algorithm}"
    assert all(slug in TECHNIQUES for slug in techniques), f"unknown technique in: {techniques}"
    return {
        "title": title,
        "algorithm": algorithm,
        "skills": skills,
        "techniques": techniques,
        "difficulty": difficulty,
        "tags": tuple(dict.fromkeys(("skill-map", "core-algorithm", algorithm, *techniques, *skills))),
        "description": description,
        "leetcodeExamples": examples,
    }


def _meta_entry(
    title: str,
    skills: tuple[str, ...],
    difficulty: str,
    description: str,
    examples: tuple[str, ...],
    source_name: str,
) -> dict[str, Any]:
    entry = _entry(title, "meta", skills, (), difficulty, description, examples)
    shared_core_tag = ("core-algorithm",) if source_name in CORE_ALGORITHM_CATALOG else ()
    entry["tags"] = tuple(dict.fromkeys(("skill-map", *shared_core_tag, "core-meta", "meta", *skills)))
    entry["sourceName"] = source_name
    return entry


CORE_ALGORITHM_CATALOG: dict[str, dict[str, Any]] = {
    "fixed_window_sum": _entry(
        "Fixed Window Sum",
        "sliding-window",
        ("fixed-vs-variable-window", "window-score-updates"),
        (),
        "Easy",
        "Track one fixed-size rolling total across an array.",
        ("Maximum Average Subarray I", "Grumpy Bookstore Owner"),
    ),
    "max_fixed_window_sum": _entry(
        "Maximum Fixed Window Sum",
        "sliding-window",
        ("fixed-vs-variable-window", "window-score-updates"),
        (),
        "Easy",
        "Update the current score by adding the entrant and removing the leaver.",
        ("Maximum Average Subarray I", "Maximum Points from Cards"),
    ),
    "min_subarray_len_at_least": _entry(
        "Minimum Valid Window",
        "sliding-window",
        ("expand-shrink-rhythm", "valid-window-rule"),
        (),
        "Med.",
        "Expand until valid, then shrink while the invariant still holds.",
        ("Minimum Size Subarray Sum", "Max Consecutive Ones III"),
    ),
    "longest_window_at_most_k_distinct": _entry(
        "At-Most-K Distinct Window",
        "sliding-window",
        ("valid-window-rule", "frequency-maps"),
        (),
        "Med.",
        "Maintain counts and shrink only when the distinct-count rule breaks.",
        ("Fruit Into Baskets", "Longest Substring with At Most K Distinct Characters"),
    ),
    "permutation_window_match": _entry(
        "Permutation Frequency Window",
        "sliding-window",
        ("frequency-maps", "fixed-vs-variable-window"),
        (),
        "Med.",
        "Compare fixed-size frequency state against a target multiset.",
        ("Permutation in String", "Find All Anagrams in a String"),
    ),
    "two_sum_sorted": _entry(
        "Sorted Two Sum Scan",
        "two-pointers",
        ("opposing-pointers", "sorted-array-leverage", "pointer-move-rule"),
        (),
        "Easy",
        "Use the current sum to decide which boundary can move.",
        ("Two Sum II", "3Sum"),
    ),
    "remove_duplicates_sorted": _entry(
        "Read/Write Deduplication",
        "two-pointers",
        ("same-direction-scan", "dedupe-rules"),
        (),
        "Easy",
        "Scan with read and compact kept values with write.",
        ("Remove Duplicates from Sorted Array", "Move Zeroes"),
    ),
    "partition_by_pivot": _entry(
        "In-Place Pivot Partition",
        "two-pointers",
        ("same-direction-scan", "sorted-array-leverage"),
        ("sorting",),
        "Med.",
        "Move selected values forward while preserving a boundary.",
        ("Sort Colors", "Partition Array"),
    ),
    "valid_palindrome": _entry(
        "Mirror Pointer Palindrome",
        "two-pointers",
        ("opposing-pointers", "pointer-move-rule"),
        (),
        "Easy",
        "Compare mirrored characters and move both sides inward.",
        ("Valid Palindrome", "Reverse String"),
    ),
    "valid_palindrome_one_delete": _entry(
        "One-Deletion Palindrome",
        "two-pointers",
        ("opposing-pointers", "pointer-move-rule"),
        (),
        "Easy",
        "Branch once when mirrored characters do not match.",
        ("Valid Palindrome II", "Almost Palindrome"),
    ),
    "binary_search": _entry(
        "Closed-Interval Binary Search",
        "binary-search",
        ("left-right-bounds", "mid-calculation", "boundary-rule-handling"),
        (),
        "Easy",
        "Probe the middle and discard one half of a closed interval.",
        ("Binary Search", "Search Insert Position"),
    ),
    "lower_bound": _entry(
        "Lower Bound",
        "binary-search",
        ("left-right-bounds", "first-last-occurrence", "boundary-rule-handling"),
        (),
        "Easy",
        "Find the first index whose value is not less than target.",
        ("Search Insert Position", "Find First and Last Position"),
    ),
    "upper_bound": _entry(
        "Upper Bound",
        "binary-search",
        ("first-last-occurrence", "boundary-rule-handling"),
        (),
        "Easy",
        "Find the first index whose value is greater than target.",
        ("Find First and Last Position", "Count Target Occurrences"),
    ),
    "search_rotated": _entry(
        "Rotated Sorted Search",
        "binary-search",
        ("left-right-bounds", "sorted-array-leverage", "boundary-rule-handling"),
        (),
        "Med.",
        "Identify the sorted half before discarding a boundary.",
        ("Search in Rotated Sorted Array", "Find Minimum in Rotated Sorted Array"),
    ),
    "binary_search_answer": _entry(
        "Search on Answer",
        "binary-search",
        ("search-on-answer", "boundary-rule-handling"),
        (),
        "Med.",
        "Binary search a monotonic feasible answer space.",
        ("Koko Eating Bananas", "Capacity To Ship Packages"),
    ),
    "preorder_recursive": _entry(
        "Recursive Preorder Traversal",
        "trees",
        ("base-case-guards", "pre-post-order-thinking"),
        ("dfs",),
        "Easy",
        "Visit node, then recurse into left and right children.",
        ("Binary Tree Preorder Traversal", "Same Tree"),
    ),
    "inorder_iterative": _entry(
        "Iterative Inorder Traversal",
        "trees",
        ("base-case-guards", "pre-post-order-thinking"),
        ("dfs", "stack"),
        "Easy",
        "Use a stack to walk left spine before visiting nodes.",
        ("Binary Tree Inorder Traversal", "Kth Smallest Element in a BST"),
    ),
    "postorder_recursive": _entry(
        "Recursive Postorder Traversal",
        "trees",
        ("pre-post-order-thinking", "base-case-guards"),
        ("dfs",),
        "Easy",
        "Recurse into children before combining at the parent.",
        ("Binary Tree Postorder Traversal", "Diameter of Binary Tree"),
    ),
    "max_tree_depth": _entry(
        "Tree Depth Recursion",
        "trees",
        ("base-case-guards", "pre-post-order-thinking"),
        ("dfs",),
        "Easy",
        "Return the child result needed by the parent.",
        ("Maximum Depth of Binary Tree", "Balanced Binary Tree"),
    ),
    "tree_has_path_sum": _entry(
        "Root-to-Leaf Path Sum",
        "trees",
        ("base-case-guards", "pre-post-order-thinking"),
        ("dfs",),
        "Easy",
        "Carry remaining target down the recursive path.",
        ("Path Sum", "Path Sum II"),
    ),
    "lowest_common_ancestor": _entry(
        "Tree Lowest Common Ancestor",
        "trees",
        ("pre-post-order-thinking", "base-case-guards"),
        ("dfs",),
        "Med.",
        "Return found targets upward and detect the split point.",
        ("Lowest Common Ancestor of a Binary Tree", "LCA of Deepest Leaves"),
    ),
    "bst_range_sum": _entry(
        "BST Range Pruning",
        "trees",
        ("boundary-rule-handling", "sorted-array-leverage"),
        ("dfs", "binary-search"),
        "Easy",
        "Use BST ordering to skip impossible subtrees.",
        ("Range Sum of BST", "Search in a BST"),
    ),
    "dfs_iterative": _entry(
        "Iterative DFS",
        "graphs",
        ("visited-tracking", "adjacency-representation"),
        ("dfs", "stack"),
        "Med.",
        "Use a stack and mark nodes before pushing new work.",
        ("Number of Islands", "Clone Graph"),
    ),
    "bfs_order": _entry(
        "Queue BFS Order",
        "graphs",
        ("queue-frontier-management", "visited-tracking", "adjacency-representation"),
        ("bfs", "queue"),
        "Med.",
        "Process a FIFO frontier while guarding against revisits.",
        ("Rotting Oranges", "Open the Lock"),
    ),
    "bfs_levels_graph": _entry(
        "BFS Level Groups",
        "graphs",
        ("level-by-level-expansion", "queue-frontier-management"),
        ("bfs", "queue"),
        "Med.",
        "Freeze the current queue length to separate BFS layers.",
        ("Binary Tree Level Order Traversal", "Word Ladder"),
    ),
    "shortest_path_unweighted": _entry(
        "Unweighted Shortest Path",
        "graphs",
        ("shortest-path-framing", "queue-frontier-management"),
        ("bfs",),
        "Med.",
        "Use BFS distance because each edge has equal cost.",
        ("Shortest Path in Binary Matrix", "Word Ladder"),
    ),
    "count_graph_components": _entry(
        "Graph Component Starts",
        "graphs",
        ("start-state-selection", "visited-tracking"),
        ("dfs",),
        "Med.",
        "Start a traversal only from unseen nodes.",
        ("Number of Connected Components", "Number of Islands"),
    ),
    "subsets": _entry(
        "Choose or Skip Subsets",
        "backtracking",
        ("choice-explore-undo", "path-state", "result-collection"),
        (),
        "Med.",
        "Explore both branches and record a copy at the leaf.",
        ("Subsets", "Subsets II"),
    ),
    "combinations": _entry(
        "Start-Index Combinations",
        "backtracking",
        ("start-index-control", "choice-explore-undo", "result-collection"),
        (),
        "Med.",
        "Advance the start index so combinations stay ordered.",
        ("Combinations", "Combination Sum III"),
    ),
    "permutations": _entry(
        "Used-Set Permutations",
        "backtracking",
        ("path-state", "choice-explore-undo", "result-collection"),
        (),
        "Med.",
        "Track used choices while building one active path.",
        ("Permutations", "Permutations II"),
    ),
    "combination_sum": _entry(
        "Pruned Combination Sum",
        "backtracking",
        ("pruning-conditions", "choice-explore-undo", "start-index-control"),
        (),
        "Med.",
        "Stop branches once sorted candidates exceed the target.",
        ("Combination Sum", "Combination Sum II"),
    ),
    "palindrome_partitions": _entry(
        "Palindrome Partition DFS",
        "backtracking",
        ("result-collection", "path-state", "pruning-conditions"),
        (),
        "Med.",
        "Choose valid prefixes and record paths at string end.",
        ("Palindrome Partitioning", "Restore IP Addresses"),
    ),
    "climb_stairs": _entry(
        "Bottom-Up Climbing Stairs",
        "dynamic-programming",
        ("base-cases", "transition-equation", "bottom-up-tabulation"),
        (),
        "Easy",
        "Seed the smallest states, then fill later states in dependency order.",
        ("Climbing Stairs", "Fibonacci Number"),
    ),
    "house_robber": _entry(
        "Top-Down Take-or-Skip DP",
        "dynamic-programming",
        ("state-definition", "transition-equation", "top-down-memoization"),
        (),
        "Med.",
        "Memoize the best result after branching between skip and take.",
        ("House Robber", "Delete and Earn"),
    ),
    "min_cost_climbing_stairs": _entry(
        "Min-Cost Transition DP",
        "dynamic-programming",
        ("transition-equation", "base-cases", "bottom-up-tabulation"),
        (),
        "Easy",
        "Compute each state from the cheaper previous step.",
        ("Min Cost Climbing Stairs", "Climbing Stairs"),
    ),
    "coin_change_min": _entry(
        "Amount-Order Coin DP",
        "dynamic-programming",
        ("iteration-order", "transition-equation", "bottom-up-tabulation"),
        (),
        "Med.",
        "Fill totals in dependency order and minimize coin count.",
        ("Coin Change", "Perfect Squares"),
    ),
    "unique_paths": _entry(
        "Bottom-Up Grid DP",
        "dynamic-programming",
        ("state-definition", "transition-equation", "bottom-up-tabulation"),
        ("grid-modeling",),
        "Med.",
        "Fill each grid state from its solved top and left dependencies.",
        ("Unique Paths", "Minimum Path Sum"),
    ),
    "longest_increasing_subsequence": _entry(
        "Bottom-Up Subsequence DP",
        "dynamic-programming",
        ("state-definition", "transition-equation", "bottom-up-tabulation"),
        (),
        "Med.",
        "Build the best subsequence ending at each state from earlier values.",
        ("Longest Increasing Subsequence", "Russian Doll Envelopes"),
    ),
    "longest_common_subsequence": _entry(
        "Bottom-Up Two-String DP",
        "dynamic-programming",
        ("state-definition", "transition-equation", "bottom-up-tabulation"),
        (),
        "Med.",
        "Fill prefix-pair states using the diagonal, top, and left dependencies.",
        ("Longest Common Subsequence", "Edit Distance"),
    ),
    "keep_top_k": _entry(
        "Top-K Min Heap",
        "heap",
        ("top-k-maintenance", "push-pop-discipline"),
        (),
        "Med.",
        "Push each candidate and prune when the heap grows past k.",
        ("Kth Largest Element in an Array", "Top K Frequent Elements"),
    ),
    "kth_largest": _entry(
        "Kth Largest Heap Top",
        "heap",
        ("top-k-maintenance", "min-vs-max-heap-choice"),
        (),
        "Med.",
        "Keep the k largest values so the heap top is kth largest.",
        ("Kth Largest Element in an Array", "Kth Largest in a Stream"),
    ),
    "merge_k_sorted_arrays": _entry(
        "Heap Frontier Merge",
        "heap",
        ("stream-processing", "push-pop-discipline"),
        (),
        "Hard",
        "Keep one frontier item per sorted source.",
        ("Merge k Sorted Lists", "Smallest Range Covering Elements from K Lists"),
    ),
    "running_kth_largest": _entry(
        "Streaming Kth Largest",
        "heap",
        ("stream-processing", "top-k-maintenance"),
        (),
        "Easy",
        "Update the top-k heap after each stream value.",
        ("Kth Largest in a Stream", "Last Stone Weight"),
    ),
    "two_heap_medians": _entry(
        "Two-Heap Running Median",
        "heap",
        ("push-pop-discipline", "stream-processing", "min-vs-max-heap-choice"),
        (),
        "Hard",
        "Balance a max-heap lower half against a min-heap upper half.",
        ("Find Median from Data Stream", "Sliding Window Median"),
    ),
    "prune_deleted_heap": _entry(
        "Lazy Heap Deletion",
        "heap",
        ("lazy-deletion-patterns", "push-pop-discipline"),
        (),
        "Hard",
        "Mark removals first and physically pop only when stale values reach the top.",
        ("Sliding Window Median", "Maximum Performance of a Team"),
    ),
    "init_parent": _entry(
        "Union-Find Parent Setup",
        "union-find",
        ("parent-initialization",),
        (),
        "Med.",
        "Start every node as its own parent and size-one component.",
        ("Number of Provinces", "Number of Connected Components"),
    ),
    "find": _entry(
        "Find with Compression",
        "union-find",
        ("find-with-compression",),
        (),
        "Med.",
        "Walk to root while shortening the parent chain.",
        ("Accounts Merge", "Number of Provinces"),
    ),
    "union_by_size": _entry(
        "Union by Size",
        "union-find",
        ("union-by-rank-size", "component-counting", "cycle-detection"),
        (),
        "Med.",
        "Attach the smaller root beneath the larger root.",
        ("Number of Connected Components", "Redundant Connection"),
    ),
    "count_components_union_find": _entry(
        "Component Count by Union",
        "union-find",
        ("component-counting", "cycle-detection"),
        (),
        "Med.",
        "Decrement component count only when two roots merge.",
        ("Number of Connected Components", "Number of Provinces"),
    ),
    "sort_intervals": _entry(
        "Sort Intervals by Boundary",
        "intervals",
        ("sort-by-start-end", "boundary-comparisons", "sorted-decisions"),
        ("sorting",),
        "Easy",
        "Order ranges so local boundary comparisons are meaningful.",
        ("Meeting Rooms", "Merge Intervals"),
    ),
    "merge_intervals": _entry(
        "Merge Overlapping Intervals",
        "intervals",
        ("merge-overlap-logic", "boundary-comparisons"),
        (),
        "Med.",
        "Append disjoint ranges and extend the current tail on overlap.",
        ("Merge Intervals", "Employee Free Time"),
    ),
    "insert_interval": _entry(
        "Insert and Merge Interval",
        "intervals",
        ("boundary-comparisons", "merge-overlap-logic"),
        (),
        "Med.",
        "Copy ranges before, merge overlaps, then append ranges after.",
        ("Insert Interval", "Merge Intervals"),
    ),
    "min_meeting_rooms": _entry(
        "Meeting Room Boundary Count",
        "intervals",
        ("room-resource-counting", "sweep-decisions"),
        ("sorting",),
        "Med.",
        "Compare sorted starts and ends to count active rooms.",
        ("Meeting Rooms II", "Minimum Number of Arrows"),
    ),
    "running_prefix": _entry(
        "Running Prefix Totals",
        "prefix-sums",
        ("running-total-setup", "constant-time-range-queries"),
        (),
        "Easy",
        "Carry a cumulative total and store each boundary prefix.",
        ("Running Sum of 1d Array", "Range Sum Query Immutable"),
    ),
    "range_sum": _entry(
        "Prefix Range Difference",
        "prefix-sums",
        ("subarray-difference-trick", "constant-time-range-queries"),
        (),
        "Easy",
        "Subtract the prefix before left from the prefix after right.",
        ("Range Sum Query Immutable", "Range Sum Query 2D"),
    ),
    "count_subarrays_sum": _entry(
        "Prefix Sum Count Map",
        "prefix-sums",
        ("sum-to-index-map", "subarray-difference-trick"),
        (),
        "Med.",
        "Count previous prefixes that would complete the target sum.",
        ("Subarray Sum Equals K", "Path Sum III"),
    ),
    "count_subarrays_divisible_by_k": _entry(
        "Modulo Prefix Buckets",
        "prefix-sums",
        ("mod-remainder-buckets", "sum-to-index-map"),
        (),
        "Med.",
        "Equal prefix remainders create divisible subarrays.",
        ("Subarray Sums Divisible by K", "Continuous Subarray Sum"),
    ),
    "matrix_prefix_sum": _entry(
        "2D Prefix Sum",
        "prefix-sums",
        ("constant-time-range-queries", "running-total-setup"),
        ("grid-modeling",),
        "Med.",
        "Build inclusion-exclusion prefixes for rectangular queries.",
        ("Range Sum Query 2D", "Matrix Block Sum"),
    ),
    "next_greater": _entry(
        "Next Greater Stack",
        "monotonic-stack",
        ("next-greater-smaller", "pop-trigger-rule"),
        (),
        "Easy",
        "Pop unresolved smaller values when the current value answers them.",
        ("Next Greater Element", "Daily Temperatures"),
    ),
    "daily_temperatures": _entry(
        "Daily Temperatures Stack",
        "monotonic-stack",
        ("next-greater-smaller", "index-storage"),
        (),
        "Med.",
        "Store indices so the answer can be a distance.",
        ("Daily Temperatures", "Online Stock Span"),
    ),
    "largest_rectangle_area": _entry(
        "Histogram Rectangle Stack",
        "monotonic-stack",
        ("pop-trigger-rule", "span-area-computation", "index-storage"),
        (),
        "Hard",
        "When height drops, popped bars receive their final span.",
        ("Largest Rectangle in Histogram", "Maximal Rectangle"),
    ),
    "sliding_window_max": _entry(
        "Monotonic Queue Window Max",
        "monotonic-stack",
        ("increasing-vs-decreasing-stack", "window-score-updates", "queue-frontier-management"),
        ("queue", "sliding-window"),
        "Hard",
        "Keep candidate indices in decreasing value order.",
        ("Sliding Window Maximum", "Constrained Subsequence Sum"),
    ),
    "valid_parentheses": _entry(
        "Balanced Parentheses Stack",
        "stacks-queues",
        ("lifo-fifo-state", "simulation"),
        ("stack",),
        "Easy",
        "Push openers and require each closer to match the top.",
        ("Valid Parentheses", "Minimum Remove to Make Valid Parentheses"),
    ),
    "eval_rpn": _entry(
        "Evaluate Reverse Polish Notation",
        "stacks-queues",
        ("simulation", "lifo-fifo-state"),
        ("stack",),
        "Med.",
        "Use the stack as deferred operands for each operator.",
        ("Evaluate Reverse Polish Notation", "Basic Calculator II"),
    ),
    "simplify_path": _entry(
        "Path Simplification Stack",
        "stacks-queues",
        ("simulation", "lifo-fifo-state"),
        ("stack",),
        "Med.",
        "Push folder names and pop for parent-directory tokens.",
        ("Simplify Path", "Crawler Log Folder"),
    ),
    "decode_string": _entry(
        "Nested Decode Stack",
        "stacks-queues",
        ("simulation", "lifo-fifo-state"),
        ("stack",),
        "Med.",
        "Save prior string and repeat count at each nested bracket.",
        ("Decode String", "Basic Calculator"),
    ),
    "min_stack_operations": _entry(
        "Min Stack State",
        "stacks-queues",
        ("min-stack-shape", "lifo-fifo-state", "simulation"),
        ("stack",),
        "Med.",
        "Mirror the value stack with a stack of current minimums.",
        ("Min Stack", "Maximum Frequency Stack"),
    ),
    "reverse_list": _entry(
        "Reverse Linked List",
        "linked-lists",
        ("pointer-rewiring", "same-direction-scan"),
        ("two-pointers",),
        "Easy",
        "Walk the list while reversing each next pointer.",
        ("Reverse Linked List", "Reverse Linked List II"),
    ),
    "merge_two_lists": _entry(
        "Merge Two Sorted Lists",
        "linked-lists",
        ("dummy-node", "pointer-rewiring", "sorted-array-leverage"),
        ("two-pointers",),
        "Easy",
        "Use a dummy tail to stitch the smaller current node.",
        ("Merge Two Sorted Lists", "Merge k Sorted Lists"),
    ),
    "has_cycle": _entry(
        "Linked List Cycle",
        "linked-lists",
        ("fast-slow-pointers", "pointer-move-rule"),
        ("two-pointers",),
        "Easy",
        "Move fast twice and slow once to detect a meeting point.",
        ("Linked List Cycle", "Find the Duplicate Number"),
    ),
    "middle_node": _entry(
        "Fast/Slow Middle Node",
        "linked-lists",
        ("fast-slow-pointers", "same-direction-scan"),
        ("two-pointers",),
        "Easy",
        "Advance fast twice so slow lands at the middle.",
        ("Middle of the Linked List", "Remove Nth Node From End"),
    ),
    "remove_nth_from_end": _entry(
        "Remove Nth from End",
        "linked-lists",
        ("fast-slow-pointers", "dummy-node", "pointer-rewiring"),
        ("two-pointers",),
        "Med.",
        "Offset fast by n, then move both pointers to find the predecessor.",
        ("Remove Nth Node From End of List", "Delete Node in a Linked List"),
    ),
    "grid_neighbors": _entry(
        "Grid Direction Neighbors",
        "matrix-grid",
        ("direction-vectors", "bounds-checks", "adjacency-representation"),
        ("grid-modeling",),
        "Easy",
        "Generate valid four-direction neighbors with bounds checks.",
        ("Number of Islands", "Flood Fill"),
    ),
    "flood_fill": _entry(
        "Grid Flood Fill",
        "matrix-grid",
        ("grid-neighbors", "visited-tracking", "queue-frontier-management"),
        ("bfs",),
        "Easy",
        "Spread from a start cell through matching neighbors.",
        ("Flood Fill", "Surrounded Regions"),
    ),
    "num_islands": _entry(
        "Number of Islands",
        "matrix-grid",
        ("grid-neighbors", "start-state-selection", "visited-tracking"),
        ("bfs",),
        "Med.",
        "Start traversal from each unvisited land cell.",
        ("Number of Islands", "Max Area of Island"),
    ),
    "oranges_rotting": _entry(
        "Multi-Source Grid BFS",
        "matrix-grid",
        ("multi-source-bfs", "queue-frontier-management", "level-by-level-expansion"),
        ("bfs",),
        "Med.",
        "Seed the queue with every source and expand by time.",
        ("Rotting Oranges", "Walls and Gates"),
    ),
    "shortest_path_grid": _entry(
        "Grid Shortest Path BFS",
        "matrix-grid",
        ("shortest-path-framing", "bounds-checks", "queue-frontier-management"),
        ("bfs",),
        "Med.",
        "Run BFS over open cells and return the first target distance.",
        ("Shortest Path in Binary Matrix", "Nearest Exit from Entrance in Maze"),
    ),
    "spiral_order": _entry(
        "Spiral Matrix Boundaries",
        "matrix-grid",
        ("bounds-checks", "boundary-comparisons"),
        (),
        "Med.",
        "Shrink four boundaries after reading each edge.",
        ("Spiral Matrix", "Rotate Image"),
    ),
    "trie_insert": _entry(
        "Trie Insert",
        "trie",
        ("prefix-tree-nodes", "character-transitions", "word-markers"),
        (),
        "Med.",
        "Create character nodes and mark the terminal word.",
        ("Implement Trie", "Design Add and Search Words Data Structure"),
    ),
    "trie_search": _entry(
        "Trie Exact Search",
        "trie",
        ("prefix-tree-nodes", "character-transitions", "word-markers"),
        (),
        "Med.",
        "Follow characters and require the final word marker.",
        ("Implement Trie", "Word Search II"),
    ),
    "trie_starts_with": _entry(
        "Trie Prefix Search",
        "trie",
        ("prefix-tree-nodes", "character-transitions"),
        (),
        "Med.",
        "Follow the prefix path without requiring a word marker.",
        ("Implement Trie", "Search Suggestions System"),
    ),
    "word_dictionary_search": _entry(
        "Trie Wildcard DFS",
        "trie",
        ("word-markers", "character-transitions", "visited-tracking"),
        ("dfs",),
        "Med.",
        "Branch over children when the pattern has a wildcard.",
        ("Design Add and Search Words Data Structure", "Word Search II"),
    ),
    "sort_by_key": _entry(
        "Sort by Decision Key",
        "sorting",
        ("sort-by-key", "sorted-decisions"),
        ("greedy",),
        "Easy",
        "Choose the ordering that makes local decisions simple.",
        ("Meeting Rooms", "Queue Reconstruction by Height"),
    ),
    "erase_overlap_intervals": _entry(
        "Greedy Non-Overlap Intervals",
        "intervals",
        ("activity-selection", "local-choice-rule", "sweep-decisions"),
        ("greedy", "sorting"),
        "Med.",
        "Keep the earliest-ending compatible interval.",
        ("Non-overlapping Intervals", "Minimum Number of Arrows"),
    ),
    "can_jump": _entry(
        "Bottom-Up Reachability DP",
        "dynamic-programming",
        ("state-definition", "transition-equation", "bottom-up-tabulation"),
        (),
        "Med.",
        "Mark each index reachable when any solved earlier state can jump to it.",
        ("Jump Game", "Gas Station"),
    ),
    "jump_game_min_jumps": _entry(
        "Bottom-Up Minimum-Jumps DP",
        "dynamic-programming",
        ("state-definition", "transition-equation", "bottom-up-tabulation"),
        (),
        "Med.",
        "Minimize each index from solved earlier states that can reach it.",
        ("Jump Game II", "Minimum Number of Taps"),
    ),
    "partition_labels": _entry(
        "Partition Labels Greedy",
        "intervals",
        ("sorted-decisions", "boundary-comparisons", "local-choice-rule"),
        ("greedy", "sorting"),
        "Med.",
        "Extend the current segment to the farthest last occurrence.",
        ("Partition Labels", "Merge Intervals"),
    ),
    "build_indegree": _entry(
        "Build Indegree Map",
        "graphs",
        ("indegree-bookkeeping", "topological-ordering"),
        ("topological-sort",),
        "Med.",
        "Count remaining prerequisites for every graph node.",
        ("Course Schedule", "Course Schedule II"),
    ),
    "topo_order": _entry(
        "Kahn Topological Order",
        "graphs",
        ("topological-ordering", "indegree-bookkeeping"),
        ("topological-sort", "bfs"),
        "Med.",
        "Process zero-indegree nodes and release their neighbors.",
        ("Course Schedule II", "Alien Dictionary"),
    ),
    "has_cycle_directed": _entry(
        "Directed Cycle by Toposort",
        "graphs",
        ("cycle-detection", "topological-ordering", "indegree-bookkeeping"),
        ("topological-sort",),
        "Med.",
        "A directed graph has a cycle when topological order misses nodes.",
        ("Course Schedule", "Find Eventual Safe States"),
    ),
}


CORE_META_CATALOG: dict[str, dict[str, Any]] = {
    "meta_clone_graph": _meta_entry(
        "Clone Graph",
        ("graph-cloning", "visited-map", "neighbor-wiring"),
        "Med.",
        "Copy each graph node once, then wire cloned neighbors from the visited map.",
        ("Clone Graph",),
        "clone_graph",
    ),
    "meta_nested_list_weight_sum": _meta_entry(
        "Nested List Weight Sum",
        ("nested-traversal", "depth-tracking", "weighted-accumulation"),
        "Med.",
        "Traverse nested values level by level while carrying the current depth.",
        ("Nested List Weight Sum",),
        "nested_list_weight_sum",
    ),
    "MetaValidWordAbbr": _meta_entry(
        "Unique Word Abbreviation",
        ("string-encoding", "collision-detection", "uniqueness-lookup"),
        "Med.",
        "Map each abbreviation to the set of original words that can produce it.",
        ("Unique Word Abbreviation",),
        "ValidWordAbbr",
    ),
    "meta_destination_city": _meta_entry(
        "Destination City",
        ("set-difference", "terminal-node", "directed-path"),
        "Easy",
        "Track outgoing cities, then find the city that never appears as a start.",
        ("Destination City",),
        "dest_city",
    ),
    "MetaParentPointerLCA": _meta_entry(
        "LCA With Parent Pointers",
        ("parent-pointers", "depth-alignment", "ancestor-walk"),
        "Med.",
        "Align node depths with parent pointers, then climb together to the meeting node.",
        ("Lowest Common Ancestor of a Binary Tree III",),
        "ParentPointerLCA",
    ),
    "MetaNextPermutation": _meta_entry(
        "Next Permutation",
        ("pivot-search", "suffix-reversal", "next-greater-swap"),
        "Med.",
        "Find the rightmost rising pivot, swap with the next greater suffix value, then reverse the suffix.",
        ("Next Permutation",),
        "NextPermutation",
    ),
    "meta_lowest_common_ancestor_bst": _meta_entry(
        "BST Lowest Common Ancestor",
        ("bst-pruning", "split-detection", "ordered-branching"),
        "Easy",
        "Use BST ordering to recurse toward both targets until their paths split.",
        ("Lowest Common Ancestor of a Binary Search Tree",),
        "lowest_common_ancestor_bst",
    ),
    "meta_top_k_frequent": _meta_entry(
        "Top K Frequent Elements",
        ("frequency-map", "top-k-selection", "heap-or-quickselect"),
        "Med.",
        "Count values, then select the k keys with the highest frequencies.",
        ("Top K Frequent Elements",),
        "top_k_frequent",
    ),
    "MetaMovingAverage": _meta_entry(
        "Moving Average From Data Stream",
        ("fixed-window-queue", "running-sum", "stream-processing"),
        "Easy",
        "Keep the most recent values in a fixed-size stream window and average that window.",
        ("Moving Average from Data Stream",),
        "MovingAverage",
    ),
    "meta_merge_intervals": _meta_entry(
        "Merge Intervals",
        ("sort-by-start", "merge-overlap", "boundary-comparison"),
        "Med.",
        "Sort intervals by start and extend the previous merged interval when boundaries overlap.",
        ("Merge Intervals",),
        "merge_intervals",
    ),
    "meta_valid_parentheses": _meta_entry(
        "Valid Parentheses",
        ("stack-matching", "open-close-pairs", "invalid-close-guard"),
        "Easy",
        "Push opens and require each close to match the latest unmatched open.",
        ("Valid Parentheses",),
        "valid_parentheses",
    ),
    "meta_top_k_heap": _meta_entry(
        "Kth Largest Element",
        ("min-heap-of-size-k", "candidate-pruning", "order-statistic"),
        "Med.",
        "Maintain a min-heap of the k largest seen values so the root is the answer.",
        ("Kth Largest Element in an Array",),
        "kth_largest_heap",
    ),
    "meta_custom_sort_string": _meta_entry(
        "Custom Sort String",
        ("rank-map", "custom-ordering", "stable-tail"),
        "Med.",
        "Sort characters by their custom alphabet rank while leaving unknown characters after ranked ones.",
        ("Custom Sort String",),
        "custom_sort_string",
    ),
    "meta_simplify_path": _meta_entry(
        "Simplify Path",
        ("path-normalization", "folder-stack", "root-boundary"),
        "Med.",
        "Treat path segments as stack operations and rebuild the canonical absolute path.",
        ("Simplify Path",),
        "simplify_path",
    ),
    "meta_vertical_order_traversal": _meta_entry(
        "Vertical Order Traversal",
        ("column-indexing", "level-order-traversal", "ordered-grouping"),
        "Hard",
        "Collect tree nodes by column and row, then return values in sorted vertical order.",
        ("Vertical Order Traversal of a Binary Tree",),
        "vertical_order_traversal",
    ),
    "meta_valid_palindrome": _meta_entry(
        "Valid Palindrome",
        ("opposing-pointers", "alphanumeric-filter", "case-folded-compare"),
        "Easy",
        "Move inward over non-alphanumeric characters and compare normalized characters.",
        ("Valid Palindrome",),
        "valid_palindrome",
    ),
    "meta_range_sum_bst": _meta_entry(
        "Range Sum of BST",
        ("tree-dfs", "range-bounds", "sum-accumulation"),
        "Easy",
        "Traverse the tree and accumulate node values that fall inside the target range.",
        ("Range Sum of BST",),
        "range_sum_bst",
    ),
    "MetaStockPrice": _meta_entry(
        "Stock Price Fluctuation",
        ("timestamp-map", "frequency-bookkeeping", "current-min-max"),
        "Med.",
        "Track timestamp corrections separately from price frequencies and the latest timestamp.",
        ("Stock Price Fluctuation",),
        "StockPrice",
    ),
    "meta_unique_paths_dp": _meta_entry(
        "Unique Paths",
        ("grid-dp", "state-transition", "base-row-column"),
        "Med.",
        "Fill each grid cell with the number of ways to reach it from top or left.",
        ("Unique Paths",),
        "unique_paths_dp",
    ),
}


CORE_PRACTICE_CATALOG: dict[str, dict[str, Any]] = {
    **CORE_ALGORITHM_CATALOG,
    **CORE_META_CATALOG,
}


def problem_slugs_for_skill(skill: str) -> tuple[str, ...]:
    skill_key = taxonomy_slug(skill)
    exact = [
        name
        for name, meta in CORE_PRACTICE_CATALOG.items()
        if skill_key in meta["skills"]
    ]
    if exact:
        return tuple(exact)
    return tuple(
        name
        for name, meta in CORE_PRACTICE_CATALOG.items()
        if skill_key == meta["algorithm"] or skill_key in meta["techniques"]
    )
