from __future__ import annotations

import re
from typing import Any


def pattern_slug(value: str) -> str:
    slug = re.sub(
        r"\s+",
        "-",
        re.sub(r"[^a-z0-9\s-]", " ", str(value or "").lower().replace("/", " ").replace("&", " ").replace("-", " ")).strip(),
    )
    return {
        "heap-priority-queue": "heap",
        "dfs-bfs": "dfs-bfs",
    }.get(slug, slug)


def method_slug(value: str) -> str:
    return pattern_slug(value)


def _entry(
    title: str,
    patterns: tuple[str, ...],
    methods: tuple[str, ...],
    difficulty: str,
    description: str,
    examples: tuple[str, ...],
) -> dict[str, Any]:
    return {
        "title": title,
        "patterns": patterns,
        "methods": methods,
        "difficulty": difficulty,
        "tags": tuple(dict.fromkeys(("skill-map", "core-algorithm", *patterns, *methods))),
        "description": description,
        "leetcodeExamples": examples,
    }


CORE_ALGORITHM_CATALOG: dict[str, dict[str, Any]] = {
    "fixed_window_sum": _entry(
        "Fixed Window Sum",
        ("sliding-window",),
        ("fixed-vs-variable-window", "window-score-updates"),
        "Easy",
        "Track one fixed-size rolling total across an array.",
        ("Maximum Average Subarray I", "Grumpy Bookstore Owner"),
    ),
    "max_fixed_window_sum": _entry(
        "Maximum Fixed Window Sum",
        ("sliding-window",),
        ("fixed-vs-variable-window", "window-score-updates"),
        "Easy",
        "Update the current score by adding the entrant and removing the leaver.",
        ("Maximum Average Subarray I", "Maximum Points from Cards"),
    ),
    "min_subarray_len_at_least": _entry(
        "Minimum Valid Window",
        ("sliding-window",),
        ("expand-shrink-rhythm", "valid-window-rule"),
        "Med.",
        "Expand until valid, then shrink while the invariant still holds.",
        ("Minimum Size Subarray Sum", "Max Consecutive Ones III"),
    ),
    "longest_window_at_most_k_distinct": _entry(
        "At-Most-K Distinct Window",
        ("sliding-window",),
        ("valid-window-rule", "frequency-maps"),
        "Med.",
        "Maintain counts and shrink only when the distinct-count rule breaks.",
        ("Fruit Into Baskets", "Longest Substring with At Most K Distinct Characters"),
    ),
    "permutation_window_match": _entry(
        "Permutation Frequency Window",
        ("sliding-window",),
        ("frequency-maps", "fixed-vs-variable-window"),
        "Med.",
        "Compare fixed-size frequency state against a target multiset.",
        ("Permutation in String", "Find All Anagrams in a String"),
    ),
    "two_sum_sorted": _entry(
        "Sorted Two Sum Scan",
        ("two-pointers",),
        ("opposing-pointers", "sorted-array-leverage", "pointer-move-rule"),
        "Easy",
        "Use the current sum to decide which boundary can move.",
        ("Two Sum II", "3Sum"),
    ),
    "remove_duplicates_sorted": _entry(
        "Read/Write Deduplication",
        ("two-pointers",),
        ("same-direction-scan", "dedupe-rules"),
        "Easy",
        "Scan with read and compact kept values with write.",
        ("Remove Duplicates from Sorted Array", "Move Zeroes"),
    ),
    "partition_by_pivot": _entry(
        "In-Place Pivot Partition",
        ("two-pointers", "greedy-sorting"),
        ("same-direction-scan", "sorted-array-leverage"),
        "Med.",
        "Move selected values forward while preserving a boundary.",
        ("Sort Colors", "Partition Array"),
    ),
    "valid_palindrome": _entry(
        "Mirror Pointer Palindrome",
        ("two-pointers",),
        ("opposing-pointers", "pointer-move-rule"),
        "Easy",
        "Compare mirrored characters and move both sides inward.",
        ("Valid Palindrome", "Reverse String"),
    ),
    "valid_palindrome_one_delete": _entry(
        "One-Deletion Palindrome",
        ("two-pointers",),
        ("opposing-pointers", "pointer-move-rule"),
        "Easy",
        "Branch once when mirrored characters do not match.",
        ("Valid Palindrome II", "Almost Palindrome"),
    ),
    "binary_search": _entry(
        "Closed-Interval Binary Search",
        ("binary-search",),
        ("left-right-bounds", "mid-calculation", "boundary-rule-handling"),
        "Easy",
        "Probe the middle and discard one half of a closed interval.",
        ("Binary Search", "Search Insert Position"),
    ),
    "lower_bound": _entry(
        "Lower Bound",
        ("binary-search",),
        ("left-right-bounds", "first-last-occurrence", "boundary-rule-handling"),
        "Easy",
        "Find the first index whose value is not less than target.",
        ("Search Insert Position", "Find First and Last Position"),
    ),
    "upper_bound": _entry(
        "Upper Bound",
        ("binary-search",),
        ("first-last-occurrence", "boundary-rule-handling"),
        "Easy",
        "Find the first index whose value is greater than target.",
        ("Find First and Last Position", "Count Target Occurrences"),
    ),
    "search_rotated": _entry(
        "Rotated Sorted Search",
        ("binary-search",),
        ("left-right-bounds", "sorted-array-leverage", "boundary-rule-handling"),
        "Med.",
        "Identify the sorted half before discarding a boundary.",
        ("Search in Rotated Sorted Array", "Find Minimum in Rotated Sorted Array"),
    ),
    "binary_search_answer": _entry(
        "Search on Answer",
        ("binary-search",),
        ("search-on-answer", "boundary-rule-handling"),
        "Med.",
        "Binary search a monotonic feasible answer space.",
        ("Koko Eating Bananas", "Capacity To Ship Packages"),
    ),
    "preorder_recursive": _entry(
        "Recursive Preorder Traversal",
        ("trees", "dfs-bfs"),
        ("base-case-guards", "pre-post-order-thinking"),
        "Easy",
        "Visit node, then recurse into left and right children.",
        ("Binary Tree Preorder Traversal", "Same Tree"),
    ),
    "inorder_iterative": _entry(
        "Iterative Inorder Traversal",
        ("trees", "stacks-queues"),
        ("base-case-guards", "pre-post-order-thinking"),
        "Easy",
        "Use a stack to walk left spine before visiting nodes.",
        ("Binary Tree Inorder Traversal", "Kth Smallest Element in a BST"),
    ),
    "postorder_recursive": _entry(
        "Recursive Postorder Traversal",
        ("trees", "dfs-bfs"),
        ("pre-post-order-thinking", "base-case-guards"),
        "Easy",
        "Recurse into children before combining at the parent.",
        ("Binary Tree Postorder Traversal", "Diameter of Binary Tree"),
    ),
    "max_tree_depth": _entry(
        "Tree Depth Recursion",
        ("trees", "dfs-bfs"),
        ("base-case-guards", "pre-post-order-thinking"),
        "Easy",
        "Return the child result needed by the parent.",
        ("Maximum Depth of Binary Tree", "Balanced Binary Tree"),
    ),
    "tree_has_path_sum": _entry(
        "Root-to-Leaf Path Sum",
        ("trees", "dfs-bfs"),
        ("base-case-guards", "pre-post-order-thinking"),
        "Easy",
        "Carry remaining target down the recursive path.",
        ("Path Sum", "Path Sum II"),
    ),
    "lowest_common_ancestor": _entry(
        "Tree Lowest Common Ancestor",
        ("trees", "dfs-bfs"),
        ("pre-post-order-thinking", "base-case-guards"),
        "Med.",
        "Return found targets upward and detect the split point.",
        ("Lowest Common Ancestor of a Binary Tree", "LCA of Deepest Leaves"),
    ),
    "bst_range_sum": _entry(
        "BST Range Pruning",
        ("trees", "binary-search"),
        ("boundary-rule-handling", "sorted-array-leverage"),
        "Easy",
        "Use BST ordering to skip impossible subtrees.",
        ("Range Sum of BST", "Search in a BST"),
    ),
    "dfs_iterative": _entry(
        "Iterative DFS",
        ("dfs-bfs", "graph-traversal"),
        ("visited-tracking", "adjacency-representation"),
        "Med.",
        "Use a stack and mark nodes before pushing new work.",
        ("Number of Islands", "Clone Graph"),
    ),
    "bfs_order": _entry(
        "Queue BFS Order",
        ("dfs-bfs", "graph-traversal", "stacks-queues"),
        ("queue-frontier-management", "visited-tracking", "adjacency-representation"),
        "Med.",
        "Process a FIFO frontier while guarding against revisits.",
        ("Rotting Oranges", "Open the Lock"),
    ),
    "bfs_levels_graph": _entry(
        "BFS Level Groups",
        ("dfs-bfs", "graph-traversal", "stacks-queues"),
        ("level-by-level-expansion", "queue-frontier-management"),
        "Med.",
        "Freeze the current queue length to separate BFS layers.",
        ("Binary Tree Level Order Traversal", "Word Ladder"),
    ),
    "shortest_path_unweighted": _entry(
        "Unweighted Shortest Path",
        ("dfs-bfs", "graph-traversal"),
        ("shortest-path-framing", "queue-frontier-management"),
        "Med.",
        "Use BFS distance because each edge has equal cost.",
        ("Shortest Path in Binary Matrix", "Word Ladder"),
    ),
    "count_graph_components": _entry(
        "Graph Component Starts",
        ("graph-traversal", "dfs-bfs"),
        ("start-state-selection", "visited-tracking"),
        "Med.",
        "Start a traversal only from unseen nodes.",
        ("Number of Connected Components", "Number of Islands"),
    ),
    "subsets": _entry(
        "Choose or Skip Subsets",
        ("backtracking",),
        ("choice-explore-undo", "path-state", "result-collection"),
        "Med.",
        "Explore both branches and record a copy at the leaf.",
        ("Subsets", "Subsets II"),
    ),
    "combinations": _entry(
        "Start-Index Combinations",
        ("backtracking",),
        ("start-index-control", "choice-explore-undo", "result-collection"),
        "Med.",
        "Advance the start index so combinations stay ordered.",
        ("Combinations", "Combination Sum III"),
    ),
    "permutations": _entry(
        "Used-Set Permutations",
        ("backtracking",),
        ("path-state", "choice-explore-undo", "result-collection"),
        "Med.",
        "Track used choices while building one active path.",
        ("Permutations", "Permutations II"),
    ),
    "combination_sum": _entry(
        "Pruned Combination Sum",
        ("backtracking",),
        ("pruning-conditions", "choice-explore-undo", "start-index-control"),
        "Med.",
        "Stop branches once sorted candidates exceed the target.",
        ("Combination Sum", "Combination Sum II"),
    ),
    "palindrome_partitions": _entry(
        "Palindrome Partition DFS",
        ("backtracking",),
        ("result-collection", "path-state", "pruning-conditions"),
        "Med.",
        "Choose valid prefixes and record paths at string end.",
        ("Palindrome Partitioning", "Restore IP Addresses"),
    ),
    "climb_stairs": _entry(
        "DP Base Cases",
        ("dynamic-programming",),
        ("base-cases", "transition-equation", "space-optimization"),
        "Easy",
        "Seed tiny answers before applying the recurrence.",
        ("Climbing Stairs", "Fibonacci Number"),
    ),
    "house_robber": _entry(
        "Rolling Take-or-Skip DP",
        ("dynamic-programming",),
        ("state-definition", "transition-equation", "space-optimization"),
        "Med.",
        "Keep only the previous take and skip states.",
        ("House Robber", "Delete and Earn"),
    ),
    "min_cost_climbing_stairs": _entry(
        "Min-Cost Transition DP",
        ("dynamic-programming",),
        ("transition-equation", "base-cases", "iteration-order"),
        "Easy",
        "Compute each state from the cheaper previous step.",
        ("Min Cost Climbing Stairs", "Climbing Stairs"),
    ),
    "coin_change_min": _entry(
        "Amount-Order Coin DP",
        ("dynamic-programming",),
        ("iteration-order", "transition-equation", "state-definition"),
        "Med.",
        "Fill totals in dependency order and minimize coin count.",
        ("Coin Change", "Perfect Squares"),
    ),
    "unique_paths": _entry(
        "Grid DP Rolling Row",
        ("dynamic-programming", "matrix-grid"),
        ("state-definition", "transition-equation", "space-optimization"),
        "Med.",
        "Accumulate path counts from top and left dependencies.",
        ("Unique Paths", "Minimum Path Sum"),
    ),
    "longest_increasing_subsequence": _entry(
        "LIS Tails Binary Search",
        ("dynamic-programming", "binary-search"),
        ("state-definition", "iteration-order", "left-right-bounds"),
        "Med.",
        "Maintain the best tail value for each subsequence length.",
        ("Longest Increasing Subsequence", "Russian Doll Envelopes"),
    ),
    "longest_common_subsequence": _entry(
        "Two-String Rolling DP",
        ("dynamic-programming",),
        ("state-definition", "transition-equation", "iteration-order"),
        "Med.",
        "Update one row while preserving the diagonal dependency.",
        ("Longest Common Subsequence", "Edit Distance"),
    ),
    "keep_top_k": _entry(
        "Top-K Min Heap",
        ("heap",),
        ("top-k-maintenance", "push-pop-discipline"),
        "Med.",
        "Push each candidate and prune when the heap grows past k.",
        ("Kth Largest Element in an Array", "Top K Frequent Elements"),
    ),
    "kth_largest": _entry(
        "Kth Largest Heap Top",
        ("heap",),
        ("top-k-maintenance", "min-vs-max-heap-choice"),
        "Med.",
        "Keep the k largest values so the heap top is kth largest.",
        ("Kth Largest Element in an Array", "Kth Largest in a Stream"),
    ),
    "merge_k_sorted_arrays": _entry(
        "Heap Frontier Merge",
        ("heap",),
        ("stream-processing", "push-pop-discipline"),
        "Hard",
        "Keep one frontier item per sorted source.",
        ("Merge k Sorted Lists", "Smallest Range Covering Elements from K Lists"),
    ),
    "running_kth_largest": _entry(
        "Streaming Kth Largest",
        ("heap",),
        ("stream-processing", "top-k-maintenance"),
        "Easy",
        "Update the top-k heap after each stream value.",
        ("Kth Largest in a Stream", "Last Stone Weight"),
    ),
    "two_heap_medians": _entry(
        "Two-Heap Running Median",
        ("heap",),
        ("push-pop-discipline", "stream-processing", "min-vs-max-heap-choice"),
        "Hard",
        "Balance a max-heap lower half against a min-heap upper half.",
        ("Find Median from Data Stream", "Sliding Window Median"),
    ),
    "prune_deleted_heap": _entry(
        "Lazy Heap Deletion",
        ("heap",),
        ("lazy-deletion-patterns", "push-pop-discipline"),
        "Hard",
        "Mark removals first and physically pop only when stale values reach the top.",
        ("Sliding Window Median", "Maximum Performance of a Team"),
    ),
    "init_parent": _entry(
        "Union-Find Parent Setup",
        ("union-find",),
        ("parent-initialization",),
        "Med.",
        "Start every node as its own parent and size-one component.",
        ("Number of Provinces", "Number of Connected Components"),
    ),
    "find": _entry(
        "Find with Compression",
        ("union-find",),
        ("find-with-compression",),
        "Med.",
        "Walk to root while shortening the parent chain.",
        ("Accounts Merge", "Number of Provinces"),
    ),
    "union_by_size": _entry(
        "Union by Size",
        ("union-find",),
        ("union-by-rank-size", "component-counting", "cycle-detection"),
        "Med.",
        "Attach the smaller root beneath the larger root.",
        ("Number of Connected Components", "Redundant Connection"),
    ),
    "count_components_union_find": _entry(
        "Component Count by Union",
        ("union-find",),
        ("component-counting", "cycle-detection"),
        "Med.",
        "Decrement component count only when two roots merge.",
        ("Number of Connected Components", "Number of Provinces"),
    ),
    "sort_intervals": _entry(
        "Sort Intervals by Boundary",
        ("intervals", "greedy-sorting"),
        ("sort-by-start-end", "boundary-comparisons", "sorted-decisions"),
        "Easy",
        "Order ranges so local boundary comparisons are meaningful.",
        ("Meeting Rooms", "Merge Intervals"),
    ),
    "merge_intervals": _entry(
        "Merge Overlapping Intervals",
        ("intervals",),
        ("merge-overlap-logic", "boundary-comparisons"),
        "Med.",
        "Append disjoint ranges and extend the current tail on overlap.",
        ("Merge Intervals", "Employee Free Time"),
    ),
    "insert_interval": _entry(
        "Insert and Merge Interval",
        ("intervals",),
        ("boundary-comparisons", "merge-overlap-logic"),
        "Med.",
        "Copy ranges before, merge overlaps, then append ranges after.",
        ("Insert Interval", "Merge Intervals"),
    ),
    "min_meeting_rooms": _entry(
        "Meeting Room Boundary Count",
        ("intervals",),
        ("room-resource-counting", "sweep-decisions"),
        "Med.",
        "Compare sorted starts and ends to count active rooms.",
        ("Meeting Rooms II", "Minimum Number of Arrows"),
    ),
    "running_prefix": _entry(
        "Running Prefix Totals",
        ("prefix-sums",),
        ("running-total-setup", "constant-time-range-queries"),
        "Easy",
        "Carry a cumulative total and store each boundary prefix.",
        ("Running Sum of 1d Array", "Range Sum Query Immutable"),
    ),
    "range_sum": _entry(
        "Prefix Range Difference",
        ("prefix-sums",),
        ("subarray-difference-trick", "constant-time-range-queries"),
        "Easy",
        "Subtract the prefix before left from the prefix after right.",
        ("Range Sum Query Immutable", "Range Sum Query 2D"),
    ),
    "count_subarrays_sum": _entry(
        "Prefix Sum Count Map",
        ("prefix-sums",),
        ("sum-to-index-map", "subarray-difference-trick"),
        "Med.",
        "Count previous prefixes that would complete the target sum.",
        ("Subarray Sum Equals K", "Path Sum III"),
    ),
    "count_subarrays_divisible_by_k": _entry(
        "Modulo Prefix Buckets",
        ("prefix-sums",),
        ("mod-remainder-buckets", "sum-to-index-map"),
        "Med.",
        "Equal prefix remainders create divisible subarrays.",
        ("Subarray Sums Divisible by K", "Continuous Subarray Sum"),
    ),
    "matrix_prefix_sum": _entry(
        "2D Prefix Sum",
        ("prefix-sums", "matrix-grid"),
        ("constant-time-range-queries", "running-total-setup"),
        "Med.",
        "Build inclusion-exclusion prefixes for rectangular queries.",
        ("Range Sum Query 2D", "Matrix Block Sum"),
    ),
    "next_greater": _entry(
        "Next Greater Stack",
        ("monotonic-stack",),
        ("next-greater-smaller", "pop-trigger-rule"),
        "Easy",
        "Pop unresolved smaller values when the current value answers them.",
        ("Next Greater Element", "Daily Temperatures"),
    ),
    "daily_temperatures": _entry(
        "Daily Temperatures Stack",
        ("monotonic-stack",),
        ("next-greater-smaller", "index-storage"),
        "Med.",
        "Store indices so the answer can be a distance.",
        ("Daily Temperatures", "Online Stock Span"),
    ),
    "largest_rectangle_area": _entry(
        "Histogram Rectangle Stack",
        ("monotonic-stack",),
        ("pop-trigger-rule", "span-area-computation", "index-storage"),
        "Hard",
        "When height drops, popped bars receive their final span.",
        ("Largest Rectangle in Histogram", "Maximal Rectangle"),
    ),
    "sliding_window_max": _entry(
        "Monotonic Queue Window Max",
        ("monotonic-stack", "stacks-queues", "sliding-window"),
        ("increasing-vs-decreasing-stack", "window-score-updates", "queue-frontier-management"),
        "Hard",
        "Keep candidate indices in decreasing value order.",
        ("Sliding Window Maximum", "Constrained Subsequence Sum"),
    ),
    "valid_parentheses": _entry(
        "Balanced Parentheses Stack",
        ("stacks-queues",),
        ("lifo-fifo-state", "simulation"),
        "Easy",
        "Push openers and require each closer to match the top.",
        ("Valid Parentheses", "Minimum Remove to Make Valid Parentheses"),
    ),
    "eval_rpn": _entry(
        "Evaluate Reverse Polish Notation",
        ("stacks-queues",),
        ("simulation", "lifo-fifo-state"),
        "Med.",
        "Use the stack as deferred operands for each operator.",
        ("Evaluate Reverse Polish Notation", "Basic Calculator II"),
    ),
    "simplify_path": _entry(
        "Path Simplification Stack",
        ("stacks-queues",),
        ("simulation", "lifo-fifo-state"),
        "Med.",
        "Push folder names and pop for parent-directory tokens.",
        ("Simplify Path", "Crawler Log Folder"),
    ),
    "decode_string": _entry(
        "Nested Decode Stack",
        ("stacks-queues",),
        ("simulation", "lifo-fifo-state"),
        "Med.",
        "Save prior string and repeat count at each nested bracket.",
        ("Decode String", "Basic Calculator"),
    ),
    "min_stack_operations": _entry(
        "Min Stack State",
        ("stacks-queues",),
        ("min-stack-shape", "lifo-fifo-state", "simulation"),
        "Med.",
        "Mirror the value stack with a stack of current minimums.",
        ("Min Stack", "Maximum Frequency Stack"),
    ),
    "reverse_list": _entry(
        "Reverse Linked List",
        ("linked-lists", "two-pointers"),
        ("pointer-rewiring", "same-direction-scan"),
        "Easy",
        "Walk the list while reversing each next pointer.",
        ("Reverse Linked List", "Reverse Linked List II"),
    ),
    "merge_two_lists": _entry(
        "Merge Two Sorted Lists",
        ("linked-lists", "two-pointers"),
        ("dummy-node", "pointer-rewiring", "sorted-array-leverage"),
        "Easy",
        "Use a dummy tail to stitch the smaller current node.",
        ("Merge Two Sorted Lists", "Merge k Sorted Lists"),
    ),
    "has_cycle": _entry(
        "Linked List Cycle",
        ("linked-lists", "two-pointers"),
        ("fast-slow-pointers", "pointer-move-rule"),
        "Easy",
        "Move fast twice and slow once to detect a meeting point.",
        ("Linked List Cycle", "Find the Duplicate Number"),
    ),
    "middle_node": _entry(
        "Fast/Slow Middle Node",
        ("linked-lists", "two-pointers"),
        ("fast-slow-pointers", "same-direction-scan"),
        "Easy",
        "Advance fast twice so slow lands at the middle.",
        ("Middle of the Linked List", "Remove Nth Node From End"),
    ),
    "remove_nth_from_end": _entry(
        "Remove Nth from End",
        ("linked-lists", "two-pointers"),
        ("fast-slow-pointers", "dummy-node", "pointer-rewiring"),
        "Med.",
        "Offset fast by n, then move both pointers to find the predecessor.",
        ("Remove Nth Node From End of List", "Delete Node in a Linked List"),
    ),
    "grid_neighbors": _entry(
        "Grid Direction Neighbors",
        ("matrix-grid", "graph-traversal"),
        ("direction-vectors", "bounds-checks", "adjacency-representation"),
        "Easy",
        "Generate valid four-direction neighbors with bounds checks.",
        ("Number of Islands", "Flood Fill"),
    ),
    "flood_fill": _entry(
        "Grid Flood Fill",
        ("matrix-grid", "dfs-bfs"),
        ("grid-neighbors", "visited-tracking", "queue-frontier-management"),
        "Easy",
        "Spread from a start cell through matching neighbors.",
        ("Flood Fill", "Surrounded Regions"),
    ),
    "num_islands": _entry(
        "Number of Islands",
        ("matrix-grid", "dfs-bfs", "graph-traversal"),
        ("grid-neighbors", "start-state-selection", "visited-tracking"),
        "Med.",
        "Start traversal from each unvisited land cell.",
        ("Number of Islands", "Max Area of Island"),
    ),
    "oranges_rotting": _entry(
        "Multi-Source Grid BFS",
        ("matrix-grid", "dfs-bfs"),
        ("multi-source-bfs", "queue-frontier-management", "level-by-level-expansion"),
        "Med.",
        "Seed the queue with every source and expand by time.",
        ("Rotting Oranges", "Walls and Gates"),
    ),
    "shortest_path_grid": _entry(
        "Grid Shortest Path BFS",
        ("matrix-grid", "dfs-bfs", "graph-traversal"),
        ("shortest-path-framing", "bounds-checks", "queue-frontier-management"),
        "Med.",
        "Run BFS over open cells and return the first target distance.",
        ("Shortest Path in Binary Matrix", "Nearest Exit from Entrance in Maze"),
    ),
    "spiral_order": _entry(
        "Spiral Matrix Boundaries",
        ("matrix-grid",),
        ("bounds-checks", "boundary-comparisons"),
        "Med.",
        "Shrink four boundaries after reading each edge.",
        ("Spiral Matrix", "Rotate Image"),
    ),
    "trie_insert": _entry(
        "Trie Insert",
        ("trie",),
        ("prefix-tree-nodes", "character-transitions", "word-markers"),
        "Med.",
        "Create character nodes and mark the terminal word.",
        ("Implement Trie", "Design Add and Search Words Data Structure"),
    ),
    "trie_search": _entry(
        "Trie Exact Search",
        ("trie",),
        ("prefix-tree-nodes", "character-transitions", "word-markers"),
        "Med.",
        "Follow characters and require the final word marker.",
        ("Implement Trie", "Word Search II"),
    ),
    "trie_starts_with": _entry(
        "Trie Prefix Search",
        ("trie",),
        ("prefix-tree-nodes", "character-transitions"),
        "Med.",
        "Follow the prefix path without requiring a word marker.",
        ("Implement Trie", "Search Suggestions System"),
    ),
    "word_dictionary_search": _entry(
        "Trie Wildcard DFS",
        ("trie", "dfs-bfs"),
        ("word-markers", "character-transitions", "visited-tracking"),
        "Med.",
        "Branch over children when the pattern has a wildcard.",
        ("Design Add and Search Words Data Structure", "Word Search II"),
    ),
    "sort_by_key": _entry(
        "Sort by Decision Key",
        ("greedy-sorting",),
        ("sort-by-key", "sorted-decisions"),
        "Easy",
        "Choose the ordering that makes local decisions simple.",
        ("Meeting Rooms", "Queue Reconstruction by Height"),
    ),
    "erase_overlap_intervals": _entry(
        "Greedy Non-Overlap Intervals",
        ("greedy-sorting", "intervals"),
        ("activity-selection", "local-choice-rule", "sweep-decisions"),
        "Med.",
        "Keep the earliest-ending compatible interval.",
        ("Non-overlapping Intervals", "Minimum Number of Arrows"),
    ),
    "can_jump": _entry(
        "Greedy Reachability",
        ("greedy-sorting",),
        ("local-choice-rule", "exchange-argument"),
        "Med.",
        "Carry the farthest reachable index while scanning.",
        ("Jump Game", "Gas Station"),
    ),
    "jump_game_min_jumps": _entry(
        "Greedy Jump Levels",
        ("greedy-sorting",),
        ("local-choice-rule", "exchange-argument"),
        "Med.",
        "Treat the current reachable range like one BFS layer.",
        ("Jump Game II", "Minimum Number of Taps"),
    ),
    "partition_labels": _entry(
        "Partition Labels Greedy",
        ("greedy-sorting", "intervals"),
        ("sorted-decisions", "boundary-comparisons", "local-choice-rule"),
        "Med.",
        "Extend the current segment to the farthest last occurrence.",
        ("Partition Labels", "Merge Intervals"),
    ),
    "build_indegree": _entry(
        "Build Indegree Map",
        ("topological-sort", "graph-traversal"),
        ("indegree-bookkeeping", "topological-ordering"),
        "Med.",
        "Count remaining prerequisites for every graph node.",
        ("Course Schedule", "Course Schedule II"),
    ),
    "topo_order": _entry(
        "Kahn Topological Order",
        ("topological-sort", "graph-traversal"),
        ("topological-ordering", "indegree-bookkeeping"),
        "Med.",
        "Process zero-indegree nodes and release their neighbors.",
        ("Course Schedule II", "Alien Dictionary"),
    ),
    "has_cycle_directed": _entry(
        "Directed Cycle by Toposort",
        ("topological-sort", "graph-traversal"),
        ("cycle-detection", "topological-ordering", "indegree-bookkeeping"),
        "Med.",
        "A directed graph has a cycle when topological order misses nodes.",
        ("Course Schedule", "Find Eventual Safe States"),
    ),
}


def function_names_for_skill(pattern: str, method: str) -> tuple[str, ...]:
    pattern_key = pattern_slug(pattern)
    method_key = method_slug(method)
    exact = [
        name
        for name, meta in CORE_ALGORITHM_CATALOG.items()
        if pattern_key in meta["patterns"] and method_key in meta["methods"]
    ]
    if exact:
        return tuple(exact)
    return tuple(
        name
        for name, meta in CORE_ALGORITHM_CATALOG.items()
        if pattern_key in meta["patterns"] or method_key in meta["methods"]
    )
